services:
  - type: web
    name: crypto-arbitrage-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    env:
      - key: MONGODB_URI
        value: mongodb+srv://mosesmwainaina1994:OWlondlAbn3bJuj4@cluster0.edyueep.mongodb.net/crypto-arbitrage?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: 17581758Na.
      - key: FRONTEND_URL
        value: https://website-xi-ten-52.vercel.app
